// SPDX-License-Identifier: AGPL-3.0-only
// Settings -> Access (AEON-148, ADR-003) on the mocked authz contract: people and
// their aliases, role changes with their effect, the last owner, deactivation,
// linking classic identities, invites and the one-time join link, custom roles
// without escalation, project access, agents and keys, the access log, can()
// gating, axe in both themes and the phone layout.
import { test, expect, type Page } from '@playwright/test'
import AxeBuilder from '@axe-core/playwright'
import { fixtures, mockWork, watchErrors } from './work-fixtures'
import { JONAS, LENA, ME, MIRA, accessWorld, mockAccess, type AccessWorld } from './access-fixtures'

test.beforeEach(async ({ page }) => { await page.clock.setSystemTime(new Date('2026-09-23T12:00:00Z')) })

async function open(page: Page, path = '/settings/access/people', options: Parameters<typeof accessWorld>[0] = {}): Promise<AccessWorld> {
  await mockWork(page, fixtures())
  const world = accessWorld(options)
  await mockAccess(page, world)
  await page.goto(path)
  await expect(page.locator('.access-card .panel > :not(.set-skeleton)').first()).toBeVisible()
  return world
}
const people = (page: Page) => page.getByRole('table', { name: 'People' })
const row = (page: Page, name: string) => people(page).locator('tr.person').filter({ has: page.getByRole('link', { name: new RegExp(`^${name}`) }) })
const calls = (world: AccessWorld, method: string, path: RegExp) => world.calls.filter(c => c.method === method && path.test(c.path))

test('people: one row per person, classic aliases under them, status apart from actions', async ({ page }) => {
  const errors = watchErrors(page)
  await open(page)
  await expect(people(page).locator('tr.person')).toHaveCount(6)
  const markus = row(page, 'Markus Barta')
  await expect(markus).toContainText('also known as mba (classic)')
  await expect(markus.locator('.c-status')).toHaveText('Active')
  await expect(row(page, 'Paul Steiner').locator('.c-status')).toHaveText('Deactivated')
  await expect(row(page, 'Lena Graf').locator('.c-role')).toContainText('Projects only')
  await expect(row(page, 'Lena Graf').locator('.c-proj')).toHaveText('Pharos, Aeon')
  // Aliases are not rows of their own; unlinked classic identities wait, folded.
  await expect(people(page)).not.toContainText('jw (classic)')
  const fold = page.getByRole('button', { name: /Imported from classic, no sign-in/ })
  await expect(fold).toHaveAttribute('aria-expanded', 'false')
  await expect(fold).toContainText('2')
  await page.getByRole('radio', { name: /^Deactivated/ }).click()
  await expect(people(page).locator('tr.person')).toHaveCount(1)
  await page.getByRole('radio', { name: /^All/ }).click()
  await page.getByLabel('Find a person').fill('mba')
  await expect(people(page).locator('tr.person')).toHaveCount(1)
  expect(errors).toEqual([])
})

test('a role change shows its effect first, applies, and can be undone', async ({ page }) => {
  const world = await open(page)
  await row(page, 'Jonas Weber').getByRole('button', { name: /Workspace role of Jonas Weber/ }).click()
  const picker = page.getByRole('dialog', { name: 'Role of Jonas Weber' })
  await expect(picker.getByRole('radio', { name: /^Member/ })).toHaveAttribute('aria-checked', 'true')
  await picker.getByRole('radio', { name: /^Admin/ }).click()
  await expect(picker.locator('.effect')).toContainText('Can ')
  await expect(picker.locator('.delta-h.gain')).toContainText('Gains 11')
  await expect(picker.locator('.perm', { hasText: 'Manage members' })).toBeVisible()
  expect(calls(world, 'PUT', /workspace-role/)).toHaveLength(0)
  await picker.getByRole('button', { name: 'Give Jonas Weber Admin' }).click()
  await expect(row(page, 'Jonas Weber').locator('.c-role')).toContainText('Admin')
  expect(calls(world, 'PUT', /workspace-role/).at(-1)?.body).toEqual({ role_id: 'role-admin' })
  await page.getByRole('button', { name: 'Undo' }).click()
  await expect(row(page, 'Jonas Weber').locator('.c-role')).toContainText('Member')
  expect(calls(world, 'PUT', /workspace-role/).at(-1)?.body).toEqual({ role_id: 'role-member' })
})

test('no escalation: an admin cannot give Owner, and is told why', async ({ page }) => {
  await open(page, '/settings/access/people', { role: 'admin' })
  await row(page, 'Mira Holm').getByRole('button', { name: /Workspace role of Mira Holm/ }).click()
  const owner = page.getByRole('radio', { name: /^Owner/ })
  await expect(owner).toContainText('Includes a permission you do not hold: Manage the workspace.')
  await owner.click()
  await expect(page.getByRole('button', { name: 'Give Mira Holm Owner' })).toBeDisabled()
})

test('the last owner keeps Owner, and the reason is said instead of a silent block', async ({ page }) => {
  await open(page)
  const role = row(page, 'Markus Barta').getByRole('button', { name: /Workspace role of Markus Barta/ })
  await role.click()
  const picker = page.getByRole('dialog', { name: 'Role of Markus Barta' })
  await expect(picker.locator('.locked')).toContainText('The last active owner keeps Owner')
  await expect(picker.getByRole('button', { name: 'Close' })).toBeVisible()
  await page.keyboard.press('Escape')
  await row(page, 'Markus Barta').getByRole('button', { name: 'Actions for Markus Barta' }).click()
  const deactivate = page.getByRole('menuitem', { name: /Deactivate/ })
  await expect(deactivate).toHaveAttribute('aria-disabled', 'true')
  await expect(deactivate).toContainText('The last active owner keeps Owner')
})

test('deactivating says what happens, then shows the status; reactivating brings them back', async ({ page }) => {
  const world = await open(page)
  await row(page, 'Mira Holm').getByRole('button', { name: 'Actions for Mira Holm' }).click()
  await page.getByRole('menuitem', { name: 'Deactivate…' }).click()
  const dialog = page.getByRole('dialog', { name: 'Deactivate Mira Holm?' })
  await expect(dialog).toContainText('Mira is signed out everywhere and cannot sign in again.')
  await expect(dialog).toContainText('Their agent keys are revoked at once.')
  await expect(dialog).toContainText('Their tickets, comments and history stay')
  await dialog.getByRole('button', { name: 'Deactivate Mira' }).click()
  await expect(row(page, 'Mira Holm').locator('.c-status')).toHaveText('Deactivated')
  expect(calls(world, 'POST', new RegExp(`/members/${MIRA}/deactivate`))).toHaveLength(1)
  // The person sheet offers the way back.
  await row(page, 'Mira Holm').getByRole('link', { name: /^Mira Holm/ }).click()
  await expect(page).toHaveURL(`/settings/access/people/${MIRA}`)
  const sheet = page.getByRole('dialog', { name: 'Mira Holm, access' })
  await sheet.getByRole('button', { name: 'Reactivate Mira' }).click()
  await expect(sheet.locator('.facts')).toContainText('Active')
  await sheet.getByRole('button', { name: 'Close Mira Holm, access' }).click()
  await expect(page).toHaveURL('/settings/access/people')
})

test('linking a classic identity to a person, with undo', async ({ page }) => {
  const world = await open(page)
  await page.getByRole('button', { name: /Imported from classic, no sign-in/ }).click()
  await page.getByRole('button', { name: 'Link jw (classic) to a person' }).click()
  const picker = page.getByRole('dialog', { name: 'Link jw (classic) to' })
  await picker.getByLabel(/Search link/i).fill('jonas')
  await picker.getByRole('option', { name: /Jonas Weber/ }).click()
  await expect(row(page, 'Jonas Weber')).toContainText('also known as jw (classic)')
  expect(calls(world, 'POST', new RegExp(`/members/${JONAS}/aliases`)).at(-1)?.body).toEqual({ from_principal_id: world.people.find(p => p.principal_id === JONAS)!.aliases[0]!.principal_id })
  await expect(page.getByRole('button', { name: /Imported from classic/ })).toContainText('1')
  await page.getByRole('button', { name: 'Undo' }).click()
  await expect(row(page, 'Jonas Weber')).not.toContainText('also known as')
})

test('invite by email: checked fields, a one-time join link to copy, then revoke', async ({ page, context }) => {
  await context.grantPermissions(['clipboard-read', 'clipboard-write'])
  const world = await open(page, '/settings/access/invites')
  await expect(page.getByText('Aeon never sends email.').first()).toBeVisible()
  await page.getByRole('button', { name: 'Invite people' }).click()
  const sheet = page.getByRole('dialog', { name: 'Invite people' })
  await sheet.getByRole('button', { name: 'Create invite link' }).click()
  await expect(sheet.getByText('Enter the email address they sign in with.')).toBeVisible()
  await expect(sheet.getByLabel('Email')).toBeFocused()
  // The server's reason lands on the field it names.
  await sheet.getByLabel('Email').fill('anna@studio.at')
  await sheet.getByRole('button', { name: 'Create invite link' }).click()
  await expect(sheet.locator('#email-error')).toContainText('There is already a pending invite for anna@studio.at')
  await sheet.getByLabel('Email').fill('nora@studio.at')
  await sheet.getByLabel('Workspace role').selectOption({ label: 'None: only the projects below' })
  await sheet.getByRole('button', { name: 'Create invite link' }).click()
  await expect(sheet.getByRole('alert')).toContainText('Give a workspace role or at least one project')
  await sheet.getByRole('button', { name: 'Add a project' }).click()
  await sheet.getByLabel('Role on project 1').selectOption({ label: 'Guest' })
  await sheet.getByRole('button', { name: 'Create invite link' }).click()
  const ready = page.getByRole('dialog', { name: 'Invite ready' })
  await expect(ready).toContainText('This link is shown only now')
  await expect(ready.getByLabel('Join link')).toHaveValue(/\/join\/tok_/)
  await ready.getByRole('button', { name: 'Copy link' }).click()
  await expect(ready.getByRole('button', { name: 'Copied' })).toBeVisible()
  expect(await page.evaluate(() => navigator.clipboard.readText())).toMatch(/\/join\/tok_/)
  expect(calls(world, 'POST', /\/members\/invites$/).at(-1)?.body).toEqual({ email: 'nora@studio.at', project_roles: [{ project_id: 'p-pharos', role_id: 'role-guest' }], expires_in_days: 14 })
  await ready.getByRole('button', { name: 'Done' }).click()
  const invite = page.getByRole('list', { name: 'Invites' }).getByRole('listitem').filter({ hasText: 'nora@studio.at' })
  await expect(invite).toContainText('Guest on Pharos')
  await expect(invite).toContainText('Pending')
  await invite.getByRole('button', { name: 'Revoke the invite for nora@studio.at' }).click()
  const confirm = page.getByRole('dialog', { name: 'Revoke the invite for nora@studio.at?' })
  await expect(confirm).toContainText('The join link stops working at once.')
  await confirm.getByRole('button', { name: 'Revoke invite' }).click()
  await expect(page.getByRole('list', { name: 'Invites' }).getByRole('listitem').filter({ hasText: 'nora@studio.at' })).toHaveCount(0)
  await page.getByRole('radio', { name: /^Revoked/ }).click()
  await expect(page.getByRole('list', { name: 'Invites' })).toContainText('nora@studio.at')
})

test('custom roles: duplicate, compose without escalation, see the diff, save; delete with reassignment', async ({ page }) => {
  const world = await open(page, '/settings/access/roles', { role: 'admin' })
  await page.getByRole('link', { name: /^Member/ }).click()
  await expect(page.getByText('Built-in roles come with Aeon')).toBeVisible()
  await expect(page.getByRole('checkbox', { name: /See work/ })).toBeDisabled()
  await page.getByRole('button', { name: 'Duplicate to customize' }).click()
  await expect(page).toHaveURL('/settings/access/roles/new?from=role-member')
  await page.getByLabel('Name', { exact: true }).fill('Quote lead')
  // What I do not hold stays off, with the reason.
  const workspace = page.locator('.perm', { hasText: 'Manage the workspace' })
  await expect(workspace.getByRole('checkbox')).toBeDisabled()
  await expect(workspace).toContainText('You do not hold this permission, so you cannot give it.')
  await page.getByRole('checkbox', { name: /Issue quotes/ }).check()
  await page.getByRole('checkbox', { name: /Approve hours/ }).check()
  await expect(page.locator('.vs')).toContainText('2 added')
  await expect(page.locator('.perm', { hasText: 'Issue quotes' }).locator('.risk')).toHaveText(/High risk/)
  await page.getByRole('radio', { name: /^Changes/ }).click()
  await expect(page.locator('.perm')).toHaveCount(2)
  await page.getByLabel('Find a permission').fill('hours')
  await expect(page.locator('.perm')).toHaveCount(1)
  await page.getByRole('button', { name: 'Create role' }).click()
  await expect(page).toHaveURL(/\/settings\/access\/roles\/role-custom-/)
  const created = calls(world, 'POST', /\/api\/roles$/).at(-1)!.body as { name: string; permissions: string[]; based_on: string }
  expect(created.name).toBe('Quote lead')
  expect(created.based_on).toBe('role-member')
  expect(created.permissions).toEqual(expect.arrayContaining(['quotes.issue', 'hours.approve']))
  expect(created.permissions).not.toContain('workspace.manage')
  // Delete an in-use role: its holders get the role I choose.
  await page.goto('/settings/access/roles/role-lead')
  await page.getByRole('button', { name: 'Delete role…' }).click()
  const sheet = page.getByRole('dialog', { name: 'Delete Delivery lead?' })
  await expect(sheet).toContainText('1 person or agent holds it')
  await sheet.getByLabel('Give its holders').selectOption({ label: 'Member' })
  await sheet.getByRole('button', { name: 'Delete and give Member' }).click()
  await expect(page).toHaveURL('/settings/access/roles')
  expect(calls(world, 'DELETE', /\/api\/roles\/role-lead\?reassign_to=role-member/)).toHaveLength(1)
  await expect(page.getByRole('link', { name: /^Delivery lead/ })).toHaveCount(0)
})

test('a role name the server refuses is shown at the name field', async ({ page }) => {
  await open(page, '/settings/access/roles/new')
  await page.getByLabel('Name', { exact: true }).fill('Admin')
  await page.getByRole('button', { name: 'Create role' }).click()
  await expect(page.locator('#role-name-error')).toHaveText('There is already a role called “Admin”.')
  await expect(page.getByLabel('Name', { exact: true })).toHaveAttribute('aria-invalid', 'true')
})

test('project access: through the workspace or the project; add, change and remove project roles', async ({ page }) => {
  const world = await open(page, '/settings/access/projects')
  await page.getByRole('link', { name: /PHAROS\s*Pharos/ }).click()
  await expect(page).toHaveURL('/settings/access/projects/p-pharos')
  const list = page.getByRole('list', { name: 'People on Pharos' })
  await expect(list.getByRole('listitem').filter({ hasText: 'Jonas Weber' })).toContainText('Delivery lead here · Member in the workspace')
  await expect(list.getByRole('listitem').filter({ hasText: 'Lena Graf' })).toContainText('Guest here · no workspace role')
  await expect(list.getByRole('listitem').filter({ hasText: 'Mira Holm' })).toContainText('Admin in the workspace, which reaches every project')
  // Add someone with a project role.
  await page.getByRole('button', { name: 'Add someone' }).click()
  await page.getByRole('dialog', { name: 'Add to Pharos' }).getByRole('option', { name: /Cleo Customer/ }).click()
  const picker = page.getByRole('dialog', { name: 'Role of Cleo Customer on Pharos' })
  await picker.getByRole('radio', { name: /^Guest/ }).click()
  await picker.getByRole('button', { name: 'Give Cleo Customer on Pharos Guest' }).click()
  await expect(list.getByRole('listitem').filter({ hasText: 'Cleo Customer' })).toContainText('Guest here')
  expect(calls(world, 'PUT', /\/projects\/p-pharos\/members\//).at(-1)?.body).toEqual({ role_id: 'role-guest' })
  // Remove Lena: the confirmation says she loses the project entirely.
  await list.getByRole('button', { name: 'Remove Lena Graf from Pharos' }).click()
  const confirm = page.getByRole('dialog', { name: 'Remove Lena Graf from Pharos?' })
  await expect(confirm).toContainText('Lena no longer sees Pharos.')
  await confirm.getByRole('button', { name: 'Remove from project' }).click()
  await expect(list.getByRole('listitem').filter({ hasText: 'Lena Graf' })).toHaveCount(0)
  expect(calls(world, 'DELETE', new RegExp(`/projects/p-pharos/members/${LENA}`))).toHaveLength(1)
})

test('project access is reachable from a person', async ({ page }) => {
  await open(page, `/settings/access/people/${LENA}`)
  const sheet = page.getByRole('dialog', { name: 'Lena Graf, access' })
  await expect(sheet.locator('#projects')).toContainText('Pharos')
  await sheet.getByRole('link', { name: 'Aeon' }).click()
  await expect(page).toHaveURL('/settings/access/projects/p-aeon')
  await expect(page.getByRole('heading', { name: 'Aeon', level: 3 })).toBeVisible()
})

test('agents: role and keys; a new key shows once; service principals are internal and keyless', async ({ page }) => {
  const world = await open(page, '/settings/access/agents')
  const agents = page.getByRole('list', { name: 'Agents' })
  await expect(agents).toContainText('aeon-coordinator')
  const internal = page.locator('.internal')
  await expect(internal).toContainText('System')
  await expect(internal).toContainText('Internal')
  await expect(internal.getByRole('button')).toHaveCount(0)
  const deployer = agents.getByRole('listitem').filter({ hasText: 'pharos-deployer' })
  await deployer.getByRole('button', { name: /active key/ }).click()
  await expect(deployer.locator('tbody tr')).toHaveCount(2)
  await deployer.getByRole('button', { name: 'New key' }).click()
  const sheet = page.getByRole('dialog', { name: 'New key for pharos-deployer' })
  await expect(sheet).toContainText('never more')
  await sheet.getByRole('button', { name: 'Create key' }).click()
  const ready = page.getByRole('dialog', { name: 'Key ready' })
  await expect(ready.getByLabel('New agent key')).toHaveValue(/^aeon_/)
  await expect(ready).toContainText('shown only now')
  await ready.getByRole('button', { name: 'Done' }).click()
  await expect(deployer.locator('tbody tr')).toHaveCount(3)
  await deployer.getByRole('button', { name: 'Revoke key aeon_ph4r' }).click()
  await page.getByRole('dialog', { name: /Revoke the key aeon_ph4r/ }).getByRole('button', { name: 'Revoke key' }).click()
  await expect(deployer.locator('tbody tr', { hasText: 'aeon_ph4r' }).locator('.state')).toHaveText('Revoked')
  expect(calls(world, 'DELETE', /\/agent-keys\/k2/)).toHaveLength(1)
})

test('the access log reads as sentences and filters by kind, person and words', async ({ page }) => {
  await open(page, '/settings/access/audit')
  const events = page.locator('.event')
  await expect(events).toHaveCount(9)
  await expect(events.first()).toContainText('Markus Barta linked mba (classic) to Markus Barta')
  await expect(page.locator('.event', { hasText: 'changed Jonas Weber’s role on Pharos from Member to Delivery lead' })).toBeVisible()
  await page.getByRole('button', { name: 'Invites' }).click()
  await expect(events).toHaveCount(3)
  await page.getByRole('button', { name: 'Keys' }).click()
  await expect(events).toHaveCount(4)
  await page.getByRole('button', { name: 'Clear filters' }).click()
  await page.getByLabel('Changes by or about').selectOption({ label: 'Mira Holm' })
  await expect(events).toHaveCount(3)
  await page.getByLabel('Find in the access log').fill('Lena')
  await expect(events).toHaveCount(1)
  await expect(page.locator('.audit-tab .summary')).toHaveText('1 of 9 changes')
})

test('can() decides: a member reads, and is offered nothing they may not do', async ({ page }) => {
  await open(page, '/settings/access/people', { role: 'member' })
  await expect(people(page).locator('tr.person')).toHaveCount(6)
  await expect(page.getByRole('button', { name: 'Invite people' })).toHaveCount(0)
  await expect(page.getByRole('button', { name: /Workspace role of/ })).toHaveCount(0)
  await expect(page.getByRole('tab', { name: /Access log/ })).toHaveCount(0)
  await row(page, 'Mira Holm').getByRole('button', { name: 'Actions for Mira Holm' }).click()
  await expect(page.getByRole('menu').getByRole('menuitem')).toHaveText([/Open/])
  await page.keyboard.press('Escape')
  await page.goto('/settings/access/roles/role-lead')
  await expect(page.getByRole('button', { name: /Duplicate|Delete role/ })).toHaveCount(0)
  await expect(page.getByRole('checkbox').first()).toBeDisabled()
})

test('without See members, Access is not offered at all', async ({ page }) => {
  await mockWork(page, fixtures())
  await mockAccess(page, accessWorld({ role: 'guest' }))
  await page.goto('/settings/access')
  await expect(page.getByRole('heading', { name: 'Access is for people who manage the workspace' })).toBeVisible()
  await expect(page.getByRole('navigation', { name: 'Settings sections' }).getByRole('link', { name: /Access/ })).toHaveCount(0)
})

test('tabs are a tablist: arrows move between them', async ({ page }) => {
  await open(page)
  await page.getByRole('tab', { name: /People/ }).focus()
  await page.keyboard.press('ArrowRight')
  await expect(page).toHaveURL('/settings/access/invites')
  await expect(page.getByRole('tab', { name: /Invites/ })).toBeFocused()
  await page.keyboard.press('End')
  await expect(page).toHaveURL('/settings/access/audit')
})

for (const colorScheme of ['light', 'dark'] as const) {
  test(`axe: people, a role, the invite form, project access and the log in ${colorScheme}`, async ({ page }) => {
    await page.emulateMedia({ colorScheme })
    await page.setViewportSize({ width: 1280, height: 900 })
    const scan = async (what: string) => {
      const result = await new AxeBuilder({ page }).withTags(['wcag2a', 'wcag2aa', 'wcag21a', 'wcag21aa']).analyze()
      expect(result.violations.filter(v => v.impact === 'serious' || v.impact === 'critical').map(v => `${what}: ${v.id} ${v.nodes.map(n => n.target.join(' ')).join(', ')}`)).toEqual([])
    }
    await open(page)
    await scan('people')
    await page.getByRole('button', { name: /Imported from classic/ }).click()
    await row(page, 'Jonas Weber').getByRole('button', { name: /Workspace role of Jonas Weber/ }).click()
    await page.getByRole('radio', { name: /^Admin/ }).click()
    await scan('role picker')
    await page.keyboard.press('Escape')
    await page.goto('/settings/access/roles/new?from=role-member')
    await expect(page.getByLabel('Name', { exact: true })).toBeVisible()
    await scan('role composer')
    await page.goto('/settings/access/invites')
    await page.getByRole('button', { name: 'Invite people' }).click()
    await expect(page.getByRole('dialog', { name: 'Invite people' })).toBeVisible()
    await scan('invite')
    await page.goto(`/settings/access/people/${ME}`)
    await expect(page.getByRole('dialog', { name: 'Markus Barta, access' })).toBeVisible()
    await scan('person')
    await page.goto('/settings/access/projects/p-pharos')
    await expect(page.getByRole('list', { name: 'People on Pharos' })).toBeVisible()
    await scan('project access')
    await page.goto('/settings/access/audit')
    await expect(page.locator('.event').first()).toBeVisible()
    await scan('access log')
  })
}

for (const colorScheme of ['light', 'dark'] as const) {
  test(`390: every Access tab fits the phone (${colorScheme})`, async ({ page }) => {
    await page.setViewportSize({ width: 390, height: 844 })
    await page.emulateMedia({ colorScheme })
    await open(page)
    for (const tab of ['people', 'invites', 'roles', 'roles/role-lead', 'projects', 'projects/p-pharos', 'agents', 'audit']) {
      await page.goto(`/settings/access/${tab}`)
      await expect(page.locator('.access-card .panel > :not(.set-skeleton)').first()).toBeVisible()
      await page.waitForTimeout(100)
      const cut = await page.evaluate(() => [...document.querySelectorAll<HTMLElement>('.access-card *')].filter(el => {
        const r = el.getBoundingClientRect()
        if (r.width <= 1 || r.height <= 1 || getComputedStyle(el).display === 'none') return false
        if (el.closest('.tabs')) return false
        return r.left < -0.5 || r.right > innerWidth + 0.5
      }).map(el => `${el.tagName}.${el.className}`))
      expect(cut, tab).toEqual([])
      expect(await page.evaluate(() => document.documentElement.scrollWidth <= innerWidth), tab).toBe(true)
    }
  })
}
